version: '3'

services:
  
  app:
    build: ./
    command: npm start
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    variables:
      REACT_APP_BACKEND_WS: http://localhost:8080
      REACT_APP_BACKEND_URL: http://localhost:8080
