version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    branches:
      only:
        - devel

    working_directory: ~/cicd-circleci

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - add_ssh_keys:
          fingerprints:
            - "7b:3d:87:e5:d2:25:b9:a9:e7:98:0f:4f:55:ee:0e:6d"

      - run: yarn
      - run: yarn build
      - run: rm -rf $(ls -A | grep -v dist | grep -v .git | grep -v node_modules | grep -v .circleci)  # clean up
      - run: mv dist/* .
      - run: git checkout master
      - run: git add .
      - run: git commit -m "Update GHPage"
      - run: git push origin master --force

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies