version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    branches:
      only:
        - devel

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - add_ssh_keys:
          fingerprints:
            - "ac:a0:4f:72:12:41:19:9e:2e:8c:c8:9e:cc:b3:33:31"
      
      - run: 
          working_directory: ~/app/frontend
          command: |
            yarn
            yarn build
            mv build node_modules ../
            cd .. && rm -rf $(ls -A | grep -v build | grep -v .git | grep -v node_modules | grep -v .circleci)  # clean up
            ls
            mv build/* .
            git checkout master
            git add .
            git commit -m "Update GHPage"
            git push origin master --force


      - store_artifacts:
          path: ~/app
          destination: artifact-app

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies