version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    branches:
      only:
        - devel

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies

      - add_ssh_keys:
          fingerprints:
            - "7b:3d:87:e5:d2:25:b9:a9:e7:98:0f:4f:55:ee:0e:6d"
      
      - run: 
          working_directory: ~/app/frontend
          command: |
            yarn
            yarn build
            rm -rf $(ls -A | grep -v dist | grep -v .git | grep -v node_modules | grep -v .circleci)  # clean up
            mv dist/* .
            git checkout master
            git add .
            git commit -m "Update GHPage"
            git push origin master --force

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies